// <auto-generated />
using System;
using Labb2_LINQ.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Labb2_LINQ.Migrations
{
    [DbContext(typeof(LabbDBContext))]
    partial class LabbDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Labb2_LINQ.Models.Elev", b =>
                {
                    b.Property<int>("ElevId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Efternamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Förnamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Klass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ålder")
                        .HasColumnType("int");

                    b.HasKey("ElevId");

                    b.ToTable("Elever");
                });

            modelBuilder.Entity("Labb2_LINQ.Models.ElevKurs", b =>
                {
                    b.Property<int>("ElevKursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ElevId")
                        .HasColumnType("int");

                    b.Property<int?>("KursId")
                        .HasColumnType("int");

                    b.HasKey("ElevKursId");

                    b.HasIndex("ElevId");

                    b.HasIndex("KursId");

                    b.ToTable("ElevKurs");
                });

            modelBuilder.Entity("Labb2_LINQ.Models.Kurs", b =>
                {
                    b.Property<int>("KursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KursNamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SlutDatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDatum")
                        .HasColumnType("datetime2");

                    b.HasKey("KursId");

                    b.ToTable("Kurser");
                });

            modelBuilder.Entity("Labb2_LINQ.Models.Lärare", b =>
                {
                    b.Property<int>("LärareId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Efternamn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Förnamn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LärareId");

                    b.ToTable("Lärare");
                });

            modelBuilder.Entity("Labb2_LINQ.Models.LärareKurs", b =>
                {
                    b.Property<int>("LärareKursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KursId")
                        .HasColumnType("int");

                    b.Property<int?>("LärareId")
                        .HasColumnType("int");

                    b.HasKey("LärareKursId");

                    b.HasIndex("KursId");

                    b.HasIndex("LärareId");

                    b.ToTable("LärareKurs");
                });

            modelBuilder.Entity("Labb2_LINQ.Models.Ämne", b =>
                {
                    b.Property<int>("ÄmneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Namn")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ÄmneId");

                    b.ToTable("Ämnen");
                });

            modelBuilder.Entity("Labb2_LINQ.Models.ÄmneKurs", b =>
                {
                    b.Property<int>("ÄmneKursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("KursId")
                        .HasColumnType("int");

                    b.Property<int?>("ÄmneId")
                        .HasColumnType("int");

                    b.HasKey("ÄmneKursId");

                    b.HasIndex("KursId");

                    b.HasIndex("ÄmneId");

                    b.ToTable("ÄmneKurs");
                });

            modelBuilder.Entity("Labb2_LINQ.Models.ElevKurs", b =>
                {
                    b.HasOne("Labb2_LINQ.Models.Elev", "Elev")
                        .WithMany("ElevKurs")
                        .HasForeignKey("ElevId");

                    b.HasOne("Labb2_LINQ.Models.Kurs", "Kurs")
                        .WithMany("ElevKurs")
                        .HasForeignKey("KursId");
                });

            modelBuilder.Entity("Labb2_LINQ.Models.LärareKurs", b =>
                {
                    b.HasOne("Labb2_LINQ.Models.Kurs", "Kurs")
                        .WithMany("LärareKurs")
                        .HasForeignKey("KursId");

                    b.HasOne("Labb2_LINQ.Models.Lärare", "Lärare")
                        .WithMany("LärareKurs")
                        .HasForeignKey("LärareId");
                });

            modelBuilder.Entity("Labb2_LINQ.Models.ÄmneKurs", b =>
                {
                    b.HasOne("Labb2_LINQ.Models.Kurs", "Kurs")
                        .WithMany("ÄmneKurs")
                        .HasForeignKey("KursId");

                    b.HasOne("Labb2_LINQ.Models.Ämne", "Ämne")
                        .WithMany("ÄmneKurs")
                        .HasForeignKey("ÄmneId");
                });
#pragma warning restore 612, 618
        }
    }
}
